import type { RequestData } from "@/components/request-card";

export const sampleRequests: RequestData[] = [
  {
    id: "1",
    title: "Help moving a sofa to 3rd floor",
    description: "Need 1-2 strong helpers for about 30 minutes. Building has no elevator.",
    category: "Moving help",
    location: "La Marsa",
    distance: "0.8 km",
    reward: "20 TND",
    urgency: "Urgent",
    postedAgo: "3 min ago",
    rating: 4.8,
  },
  {
    id: "2",
    title: "Fix Wi-Fi router setup",
    description: "New router won't connect properly. Need someone tech-savvy.",
    category: "Tech support",
    location: "Carthage",
    distance: "1.2 km",
    reward: "10 TND",
    urgency: "Today",
    postedAgo: "12 min ago",
    rating: 4.6,
  },
  {
    id: "3",
    title: "Pick up groceries from market",
    description: "Small list of items, payment refunded on arrival.",
    category: "Errands",
    location: "Sidi Bou Said",
    distance: "2.1 km",
    reward: "Free help",
    urgency: "This week",
    postedAgo: "1 h ago",
    rating: 5.0,
  },
  {
    id: "4",
    title: "Math tutoring for high school exam",
    description: "Need help reviewing algebra and geometry chapters.",
    category: "Study help",
    location: "Tunis Centre",
    distance: "3.4 km",
    reward: "Custom",
    urgency: "This week",
    postedAgo: "2 h ago",
    rating: 4.9,
  },
  {
    id: "5",
    title: "Assemble IKEA wardrobe",
    description: "All parts ready, just need an extra pair of hands.",
    category: "Home tasks",
    location: "Lac 2",
    distance: "4.0 km",
    reward: "20 TND",
    urgency: "Today",
    postedAgo: "20 min ago",
    rating: 4.7,
  },
  {
    id: "6",
    title: "Translate official document",
    description: "Short administrative document, French to Arabic.",
    category: "Administrative help",
    location: "Ariana",
    distance: "5.5 km",
    reward: "10 TND",
    urgency: "This week",
    postedAgo: "4 h ago",
    rating: 4.5,
  },
];
